-- LLM-Evaluated Architecture Component Classification
-- Generated by Claude (Opus 4.6) analyzing 69,402 distinct filenames
-- across 9 repositories: OpenClaw, supabase, RuVector, WordPress, Rails,
-- NPSP, openrocket, ImprovNinja, VocalRSVP
--
-- Classification strategy (priority order):
--   1. Git rename artifacts → Other
--   2. Build artifacts (Swift hashes, object files, .dll, .ser) → Build/Tooling
--   3. Test files (path + naming patterns) → Testing
--   4. Salesforce test classes (*_TEST.cls) → Testing
--   5. CI/CD & DevOps (path-based: .github, docker, scripts, infrastructure,
--      terraform, k8s, cloudbuild, install4j, snap) → DevOps/CI
--   6. Documentation (path-based) → Documentation
--   7. Front-End (path-context: studio, ui, apps/studio, swing/src,
--      Salesforce LWC/Aura, app/templates) → Front-End
--   8. Salesforce metadata (objects, labels, pages) → Database/Front-End/Configuration
--   9. Database files (migrations, schema, firestore rules) → Database
--  10. Extension-based classification → various
--  11. Filename-based (no extension) → various
--  12. Default → Other
--
-- Key LLM-informed decisions vs generic extension mapping:
--   - .ts in apps/studio/, apps/www/, studio/, ui/ → Front-End (not Back-End)
--   - .tsx → Front-End everywhere (React JSX is inherently UI)
--   - .mdx → Documentation (docs site content, not Front-End)
--   - .rb/.php in test paths → Testing (not Back-End)
--   - .cls files with _TEST suffix → Testing (Apex test classes)
--   - force-app/*/lwc/ and force-app/*/aura/ → Front-End (Salesforce UI)
--   - force-app/*/objects/ → Database (custom object metadata)
--   - robot/ → Testing (Robot Framework e2e tests)
--   - .vue, .dart, .svelte → Front-End
--   - e2e/ → Testing
--   - .claude/, .agents/, .cursor/, .idea/ → Configuration
--   - swing/src/ → Front-End (Java Swing UI, openrocket)
--   - infrastructure/, terraform/, k8s/, cloudbuild/ → DevOps/CI
--   - .java → Back-End, .gradle → Build/Tooling
--   - .ork/.eng/.orc → Assets (OpenRocket design files)
--   - .afphoto/.psd/.xcf → Assets (design source files)
--   - .rules → Database (Firestore rules)
--   - Swift build cache (.h-HASH, .swiftmodule, .pcm) → Build/Tooling
--
-- Usage:
--   Incremental mode: Execute only the UPDATE (classifies NULL rows)
--   Force mode: Execute RESET first, then UPDATE (re-classifies all rows)
--
-- GITX-146: Simplified to remove TypeScript-based classification
--           and execute SQL directly from VS Code extension

-- ============================================================================
-- RESET (Force mode only)
-- ============================================================================
-- @RESET_START
UPDATE commit_files SET arc_component = NULL;
-- @RESET_END

-- ============================================================================
-- CLASSIFICATION (Both modes - incremental only affects NULL rows)
-- ============================================================================
-- @CLASSIFY_START
UPDATE commit_files SET arc_component = CASE

  -- =========================================================================
  -- PRIORITY 1: Git rename artifacts (extensions ending in })
  -- These are diff artifacts from git renames, not real files
  -- =========================================================================
  WHEN file_extension LIKE '%}' THEN 'Other'

  -- =========================================================================
  -- PRIORITY 2: Swift/Rust build artifacts → Build/Tooling
  -- .h-HASH are Swift module cache files, .o/.d are compiler outputs
  -- =========================================================================
  WHEN file_extension LIKE '.h-%' THEN 'Build/Tooling'
  WHEN file_extension IN ('.o', '.d', '.swiftmodule', '.swiftdeps', '.swiftsourceinfo', '.swiftdoc', '.pcm', '.rmeta', '.modulemap', '.wasm') THEN 'Build/Tooling'
  WHEN file_extension IN ('.dll', '.ser') THEN 'Build/Tooling'  -- Windows DLLs, serialized Java objects

  -- =========================================================================
  -- PRIORITY 3: Test files (path-based detection)
  -- Test directories and test file naming patterns take priority over extension
  -- =========================================================================
  WHEN filename ~ '(^|/)(__tests__|tests?|spec|phpunit|fixtures)/' THEN 'Testing'
  WHEN filename ~ '(^|/)e2e/' THEN 'Testing'
  WHEN filename ~ '\.(test|spec)\.[^./]+$' THEN 'Testing'
  WHEN filename ~ '(^|/)test_[^/]+\.[^./]+$' THEN 'Testing'
  WHEN filename ~ '_test\.(ts|js|rb|py|rs|go|swift|kt|php|java)$' THEN 'Testing'
  WHEN filename ~ 'Test\.(java|kt)$' THEN 'Testing'  -- Java/Kotlin test naming convention
  WHEN filename ~ '_spec\.(ts|js|rb|py|rs)$' THEN 'Testing'
  WHEN filename ~ '(^|/)benchmarks/' THEN 'Testing'
  -- Robot Framework tests (NPSP)
  WHEN filename ~ '(^|/)robot/' THEN 'Testing'
  WHEN file_extension = '.robot' THEN 'Testing'

  -- =========================================================================
  -- PRIORITY 4: Salesforce test classes (NPSP)
  -- Apex classes ending in _TEST.cls are test files
  -- =========================================================================
  WHEN filename ~ '_TEST\.cls(-meta\.xml)?$' THEN 'Testing'
  WHEN filename ~ '_TDTM\.cls(-meta\.xml)?$' THEN 'Back-End'

  -- =========================================================================
  -- PRIORITY 5: CI/CD & DevOps (path-based)
  -- GitHub workflows, Docker configs, devcontainer, scripts
  -- =========================================================================
  WHEN filename ~ '^\.github/(workflows|actions)/' THEN 'DevOps/CI'
  WHEN filename ~ '^(\.devcontainer|docker)/' THEN 'DevOps/CI'
  WHEN filename ~ '^scripts/' THEN 'DevOps/CI'
  WHEN filename ~ '^\.githooks/' THEN 'DevOps/CI'
  WHEN filename ~ '(^|/)metadeploy/' THEN 'DevOps/CI'
  WHEN filename = 'cumulusci.yml' THEN 'DevOps/CI'
  -- Infrastructure-as-code directories (ImprovNinja, VocalRSVP)
  WHEN filename ~ '^infrastructure/' THEN 'DevOps/CI'
  WHEN filename ~ '^(terraform|k8s|cloudbuild)/' THEN 'DevOps/CI'
  -- Java packaging and installers (openrocket)
  WHEN filename ~ '^(install4j|snap)/' THEN 'DevOps/CI'
  WHEN file_extension = '.install4j' THEN 'DevOps/CI'

  -- =========================================================================
  -- PRIORITY 6: Documentation (path-based)
  -- docs/, guides/, plans/, ADRs, research, Supabase apps/docs
  -- =========================================================================
  WHEN filename ~ '^(docs|guides|plans)/' THEN 'Documentation'
  WHEN filename ~ '^apps/docs/' THEN 'Documentation'
  WHEN filename ~ '^apps/learn/' THEN 'Documentation'
  WHEN filename ~ '(^|/)vale/' THEN 'Documentation'

  -- =========================================================================
  -- PRIORITY 7: Front-End (path-context for ambiguous extensions)
  -- Covers: studio UIs, web apps, mobile apps, Salesforce LWC/Aura
  -- =========================================================================
  -- Supabase: apps/studio, apps/www, apps/ui-library, apps/design-system, etc.
  WHEN filename ~ '^apps/(studio|www|ui-library|design-system|storybook|cms|marketplace|lite-studio|studio-prototype|studio-lite|database-new|database-playground)/' AND file_extension IN ('.ts', '.js', '.tsx', '.jsx', '.css', '.scss', '.svg', '.mjs', '.json', '.mts', '.vue', '.svelte', '.html') THEN 'Front-End'
  WHEN filename ~ '^apps/(studio|www|ui-library|design-system|storybook|cms|marketplace)/' AND file_extension IN ('.png', '.jpg', '.jpeg', '.gif', '.webp', '.avif', '.ico', '.svg', '.woff2', '.woff', '.ttf', '.eot', '.mp3') THEN 'Assets'
  -- OpenClaw/RuVector: studio/, ui/
  WHEN filename ~ '^(studio|ui)/' AND file_extension IN ('.ts', '.js', '.svelte', '.tsx', '.jsx', '.css', '.scss', '.html', '.svg', '.mjs', '.json', '.mts') THEN 'Front-End'
  WHEN filename ~ '^(studio|ui)/' AND file_extension IN ('.png', '.jpg', '.jpeg', '.gif', '.webp', '.avif', '.ico', '.svg', '.woff2', '.ttf', '.mp3') THEN 'Assets'
  -- Mobile/desktop apps
  WHEN filename ~ '^apps/(macos|ios|android)/' AND file_extension IN ('.swift', '.kt', '.kts', '.ts', '.js', '.tsx', '.jsx', '.plist', '.xcconfig') THEN 'Front-End'
  -- Supabase blocks (UI components)
  WHEN filename ~ '^blocks/' THEN 'Front-End'
  -- Java Swing UI (openrocket) — swing/src/ is the desktop GUI layer
  WHEN filename ~ '^swing/' THEN 'Front-End'
  -- Python app templates (ImprovNinja)
  WHEN filename ~ '(^|/)app/templates/' THEN 'Front-End'
  -- Salesforce LWC and Aura components (NPSP)
  WHEN filename ~ '(^|/)lwc/' THEN 'Front-End'
  WHEN filename ~ '(^|/)aura/' THEN 'Front-End'
  WHEN filename ~ '(^|/)pages/' AND file_extension = '.page' THEN 'Front-End'
  WHEN filename ~ '(^|/)components/' AND file_extension = '.component' THEN 'Front-End'
  WHEN filename ~ '(^|/)flexipages/' THEN 'Front-End'

  -- =========================================================================
  -- PRIORITY 8: Salesforce metadata (NPSP)
  -- Custom objects → Database, labels/config → Configuration
  -- =========================================================================
  WHEN filename ~ '(^|/)objects/' AND file_extension IN ('.xml', '.object-meta.xml') THEN 'Database'
  WHEN filename ~ '(^|/)labels/' THEN 'Configuration'
  WHEN filename ~ '(^|/)orgs/' AND file_extension = '.json' THEN 'Configuration'
  -- Firestore rules (ImprovNinja)
  WHEN file_extension = '.rules' THEN 'Database'

  -- =========================================================================
  -- PRIORITY 9: Database files (path-based)
  -- Migrations, schema files, Supabase functions
  -- =========================================================================
  WHEN filename ~ '(^|/)migrations?/' AND file_extension = '.sql' THEN 'Database'
  WHEN filename ~ '(^|/)supabase/migrations/' THEN 'Database'
  WHEN filename ~ '(^|/)schema' AND file_extension IN ('.rb', '.sql') THEN 'Database'
  WHEN filename ~ '(^|/)supabase/functions/' THEN 'Back-End'

  -- =========================================================================
  -- PRIORITY 10: AI/Editor/IDE configuration (path-based)
  -- .claude/, .agents/, .cursor/, .idea/, .jira/ are tool configs
  -- =========================================================================
  WHEN filename ~ '^(\.claude|\.agents?|\.cursor|\.idea|\.jira|\.serena)/' THEN 'Configuration'
  -- Build system directories (openrocket Gradle, generic config)
  WHEN filename ~ '^(gradle|config)/' THEN 'Configuration'
  WHEN filename ~ '^dev-credentials/' THEN 'Configuration'

  -- =========================================================================
  -- PRIORITY 11: Extension-based classification
  -- Informed by analyzing actual file content across all 6 repositories
  -- =========================================================================

  -- Back-End: Server-side application code
  WHEN file_extension IN ('.ts', '.js', '.mjs', '.cjs', '.mts') THEN 'Back-End'
  WHEN file_extension IN ('.rs', '.rb', '.py', '.php', '.go', '.kt', '.kts', '.swift') THEN 'Back-End'
  WHEN file_extension IN ('.java') THEN 'Back-End'  -- Java (openrocket core, non-Swing caught by path above)
  WHEN file_extension IN ('.c', '.cpp', '.h', '.S', '.metal', '.wgsl') THEN 'Back-End'
  WHEN file_extension IN ('.gemspec', '.rake', '.ru', '.fcgi', '.cgi', '.servlet') THEN 'Back-End'
  WHEN file_extension IN ('.rxml', '.rhtml') THEN 'Back-End'
  WHEN file_extension = '.cls' THEN 'Back-End'  -- Salesforce Apex classes (non-test, caught above)
  WHEN file_extension = '.dart' THEN 'Front-End'  -- Flutter/Dart is client-side

  -- Front-End: Client-side UI code
  WHEN file_extension IN ('.tsx', '.jsx', '.svelte', '.vue') THEN 'Front-End'
  WHEN file_extension IN ('.html', '.css', '.scss', '.erb', '.ejs') THEN 'Front-End'
  WHEN file_extension IN ('.woff2', '.woff', '.ttf', '.eot', '.otf') THEN 'Front-End'
  WHEN file_extension IN ('.page', '.cmp', '.component', '.app') THEN 'Front-End'  -- Salesforce UI

  -- Documentation: Docs, readmes, text files, MDX (docs site content)
  WHEN file_extension IN ('.md', '.mdx', '.txt', '.TXT', '.rdoc', '.rst') THEN 'Documentation'
  WHEN file_extension IN ('.prose', '.dot', '.dia', '.graphml') THEN 'Documentation'
  WHEN file_extension IN ('.csv', '.bib') THEN 'Documentation'
  WHEN file_extension IN ('.docx', '.rtf', '.pdf') THEN 'Documentation'
  WHEN file_extension IN ('.mdc') THEN 'Documentation'  -- Cursor rules (markdown content)

  -- Database: Schema, migrations, queries, database files
  WHEN file_extension IN ('.sql', '.prisma') THEN 'Database'
  WHEN file_extension = '.db' THEN 'Database'  -- SQLite/embedded databases (openrocket)

  -- DevOps/CI: Infrastructure, CI/CD, containers, shell scripts
  WHEN file_extension IN ('.sh', '.bat', '.ps1') THEN 'DevOps/CI'
  WHEN file_extension IN ('.tf', '.tfvars') THEN 'DevOps/CI'
  WHEN file_extension IN ('.yml', '.yaml') THEN 'DevOps/CI'

  -- Configuration: Config files, env templates, project metadata
  WHEN file_extension IN ('.json', '.jsonc', '.json5', '.jsonl') THEN 'Configuration'
  WHEN file_extension IN ('.toml', '.ini', '.conf', '.xml', '.plist') THEN 'Configuration'
  WHEN file_extension IN ('.example', '.dist', '.template', '.env') THEN 'Configuration'
  WHEN file_extension IN ('.lock', '.resolved') THEN 'Configuration'
  WHEN file_extension IN ('.properties', '.xcconfig') THEN 'Configuration'
  WHEN file_extension IN ('.iml') THEN 'Configuration'  -- IntelliJ module files (openrocket)
  WHEN file_extension IN ('.po', '.mo') THEN 'Configuration'

  -- Testing: Test config files
  WHEN file_extension = '.test' THEN 'Testing'

  -- Build/Tooling: Build configs, compiled outputs, source maps
  WHEN file_extension IN ('.map', '.node', '.gyp') THEN 'Build/Tooling'
  WHEN file_extension = '.gradle' THEN 'Build/Tooling'  -- Gradle build files (openrocket)
  WHEN filename ~ '\.(gradle|settings)\.kts$' THEN 'Build/Tooling'  -- Kotlin Gradle build scripts
  WHEN file_extension IN ('.tgz', '.tar', '.zip', '.bin', '.gz') THEN 'Build/Tooling'
  WHEN file_extension IN ('.patch', '.diff', '.log') THEN 'Build/Tooling'
  WHEN file_extension IN ('.pkl', '.priors') THEN 'Build/Tooling'

  -- Assets: Images, audio, media, static resources
  WHEN file_extension IN ('.png', '.jpg', '.jpeg', '.gif', '.webp', '.avif', '.ico', '.icns') THEN 'Assets'
  WHEN file_extension IN ('.svg') THEN 'Assets'
  WHEN file_extension IN ('.mp3', '.wav', '.ogg', '.flac') THEN 'Assets'
  WHEN file_extension IN ('.mp4', '.webm', '.mov') THEN 'Assets'
  WHEN file_extension IN ('.rvf', '.dat') THEN 'Assets'
  WHEN file_extension IN ('.ork', '.eng', '.orc') THEN 'Assets'  -- OpenRocket design/engine/component files
  WHEN file_extension IN ('.afphoto', '.psd', '.xcf') THEN 'Assets'  -- Design source files (Affinity, Photoshop, GIMP)
  WHEN file_extension IN ('.pem', '.crt', '.key') THEN 'Assets'

  -- Back-End: Miscellaneous server-side
  WHEN file_extension IN ('.tt') THEN 'Back-End'

  -- Other: Backup files, unknown formats
  WHEN file_extension IN ('.backup', '.bkup', '.orig', '.sample') THEN 'Other'

  -- =========================================================================
  -- PRIORITY 12: Filename-based (no extension or special filenames)
  -- =========================================================================
  WHEN filename ~ '(^|/)Dockerfile' THEN 'DevOps/CI'
  WHEN filename ~ '(^|/)(Makefile|Rakefile|Brewfile|Gemfile|gradlew)$' THEN 'Build/Tooling'
  WHEN filename ~ '(^|/)(LICENSE|COPYING|CHANGELOG|CONTRIBUTING|README|AGENTS|SECURITY|CODE_OF_CONDUCT)' THEN 'Documentation'
  WHEN filename ~ '(^|/)\.(gitignore|gitattributes|gitmodules|gitkeep|npmignore|npmrc|eslintignore|eslintrc|prettierignore|shellcheckrc|swiftformat|gcloudignore|dockerignore|jshintrc|forceignore|mdlrc)' THEN 'Configuration'
  WHEN filename ~ '(^|/)\.(mailmap|git-blame-ignore-revs)$' THEN 'Configuration'
  WHEN filename ~ '(^|/)\.env(\..+)?$' THEN 'Configuration'
  WHEN filename ~ '(^|/)\.DS_Store$' THEN 'Other'
  WHEN filename ~ '(^|/)(CODEOWNERS|FUNDING\.yml|dependabot\.yml|labeler\.yml)$' THEN 'DevOps/CI'
  WHEN filename ~ '(^|/)(RAILS_VERSION|yarn\.lock)$' THEN 'Configuration'
  WHEN filename ~ '(^|/)Peekaboo$' THEN 'Other'
  WHEN filename ~ '(^|/)pre-commit$' THEN 'DevOps/CI'
  WHEN filename ~ '(^|/)jest\.setup\.' THEN 'Testing'
  WHEN filename ~ '(^|/)jsconfig\.json$' THEN 'Configuration'
  WHEN filename ~ '(^|/)package\.json$' THEN 'Configuration'
  WHEN filename ~ '(^|/)tsconfig' THEN 'Configuration'

  -- =========================================================================
  -- DEFAULT: Anything not matched
  -- =========================================================================
  ELSE 'Other'

END
WHERE arc_component IS NULL;
-- @CLASSIFY_END

-- ============================================================================
-- SUMMARY (executed after classification to get category breakdown)
-- ============================================================================
-- @SUMMARY_START
SELECT arc_component, COUNT(*) AS total_rows, COUNT(DISTINCT filename) AS distinct_files
FROM commit_files
WHERE arc_component IS NOT NULL
GROUP BY arc_component
ORDER BY total_rows DESC;
-- @SUMMARY_END
